//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.20 at 10:24:05 AM CEST 
//


package no.arkivverket.dataextracttools.arkade.modules.reports.session.bind;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the no.arkivverket.dataextracttools.arkade.modules.reports.session.bind package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SessionReport_QNAME = new QName("http://www.arkivverket.no/dataextracttools/arkade/sessionreport", "sessionReport");
    private final static QName _DescriptionTextBlock_QNAME = new QName("http://www.arkivverket.no/dataextracttools/arkade/sessionreport", "textBlock");
    private final static QName _DescriptionDescriptionList_QNAME = new QName("http://www.arkivverket.no/dataextracttools/arkade/sessionreport", "descriptionList");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: no.arkivverket.dataextracttools.arkade.modules.reports.session.bind
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Identifiers }
     * 
     */
    public Identifiers createIdentifiers() {
        return new Identifiers();
    }

    /**
     * Create an instance of {@link SessionReport }
     * 
     */
    public SessionReport createSessionReport() {
        return new SessionReport();
    }

    /**
     * Create an instance of {@link SessionReport.SessionInformation }
     * 
     */
    public SessionReport.SessionInformation createSessionReportSessionInformation() {
        return new SessionReport.SessionInformation();
    }

    /**
     * Create an instance of {@link InformationItem }
     * 
     */
    public InformationItem createInformationItem() {
        return new InformationItem();
    }

    /**
     * Create an instance of {@link Result }
     * 
     */
    public Result createResult() {
        return new Result();
    }

    /**
     * Create an instance of {@link ResultItem }
     * 
     */
    public ResultItem createResultItem() {
        return new ResultItem();
    }

    /**
     * Create an instance of {@link DescriptionList }
     * 
     */
    public DescriptionList createDescriptionList() {
        return new DescriptionList();
    }

    /**
     * Create an instance of {@link ListItem }
     * 
     */
    public ListItem createListItem() {
        return new ListItem();
    }

    /**
     * Create an instance of {@link InformationItems }
     * 
     */
    public InformationItems createInformationItems() {
        return new InformationItems();
    }

    /**
     * Create an instance of {@link ResultItems }
     * 
     */
    public ResultItems createResultItems() {
        return new ResultItems();
    }

    /**
     * Create an instance of {@link Description }
     * 
     */
    public Description createDescription() {
        return new Description();
    }

    /**
     * Create an instance of {@link Activities }
     * 
     */
    public Activities createActivities() {
        return new Activities();
    }

    /**
     * Create an instance of {@link Activity }
     * 
     */
    public Activity createActivity() {
        return new Activity();
    }

    /**
     * Create an instance of {@link Identifiers.Identifier }
     * 
     */
    public Identifiers.Identifier createIdentifiersIdentifier() {
        return new Identifiers.Identifier();
    }

    /**
     * Create an instance of {@link SessionReport.SessionInformation.Application }
     * 
     */
    public SessionReport.SessionInformation.Application createSessionReportSessionInformationApplication() {
        return new SessionReport.SessionInformation.Application();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SessionReport }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.arkivverket.no/dataextracttools/arkade/sessionreport", name = "sessionReport")
    public JAXBElement<SessionReport> createSessionReport(SessionReport value) {
        return new JAXBElement<SessionReport>(_SessionReport_QNAME, SessionReport.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.arkivverket.no/dataextracttools/arkade/sessionreport", name = "textBlock", scope = Description.class)
    public JAXBElement<String> createDescriptionTextBlock(String value) {
        return new JAXBElement<String>(_DescriptionTextBlock_QNAME, String.class, Description.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DescriptionList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.arkivverket.no/dataextracttools/arkade/sessionreport", name = "descriptionList", scope = Description.class)
    public JAXBElement<DescriptionList> createDescriptionDescriptionList(DescriptionList value) {
        return new JAXBElement<DescriptionList>(_DescriptionDescriptionList_QNAME, DescriptionList.class, Description.class, value);
    }

}
