//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.20 at 10:24:05 AM CEST 
//


package no.arkivverket.dataextracttools.arkade.modules.reports.session.bind;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for resultItem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="resultItem">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="identifiers" type="{http://www.arkivverket.no/dataextracttools/arkade/sessionreport}identifiers" minOccurs="0"/>
 *         &lt;element name="label" type="{http://www.arkivverket.no/dataextracttools/arkade/sessionreport}label" minOccurs="0"/>
 *         &lt;element name="content" type="{http://www.arkivverket.no/dataextracttools/arkade/sessionreport}content" minOccurs="0"/>
 *         &lt;element name="resultItems" type="{http://www.arkivverket.no/dataextracttools/arkade/sessionreport}resultItems" minOccurs="0"/>
 *         &lt;element name="descripton" type="{http://www.arkivverket.no/dataextracttools/arkade/sessionreport}description" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "resultItem", propOrder = {
    "identifiers",
    "label",
    "content",
    "resultItems",
    "descripton"
})
public class ResultItem {

    protected Identifiers identifiers;
    protected String label;
    protected String content;
    protected ResultItems resultItems;
    protected Description descripton;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "type")
    protected String type;

    /**
     * Gets the value of the identifiers property.
     * 
     * @return
     *     possible object is
     *     {@link Identifiers }
     *     
     */
    public Identifiers getIdentifiers() {
        return identifiers;
    }

    /**
     * Sets the value of the identifiers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Identifiers }
     *     
     */
    public void setIdentifiers(Identifiers value) {
        this.identifiers = value;
    }

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets the value of the content property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContent(String value) {
        this.content = value;
    }

    /**
     * Gets the value of the resultItems property.
     * 
     * @return
     *     possible object is
     *     {@link ResultItems }
     *     
     */
    public ResultItems getResultItems() {
        return resultItems;
    }

    /**
     * Sets the value of the resultItems property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResultItems }
     *     
     */
    public void setResultItems(ResultItems value) {
        this.resultItems = value;
    }

    /**
     * Gets the value of the descripton property.
     * 
     * @return
     *     possible object is
     *     {@link Description }
     *     
     */
    public Description getDescripton() {
        return descripton;
    }

    /**
     * Sets the value of the descripton property.
     * 
     * @param value
     *     allowed object is
     *     {@link Description }
     *     
     */
    public void setDescripton(Description value) {
        this.descripton = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

}
