//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.20 at 10:24:05 AM CEST 
//


package no.arkivverket.dataextracttools.arkade.modules.reports.session.bind;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for sessionReport complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sessionReport">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sessionInformation" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="identifiers" type="{http://www.arkivverket.no/dataextracttools/arkade/sessionreport}identifiers" minOccurs="0"/>
 *                   &lt;element name="timeCreated" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *                   &lt;element name="createdBy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="application" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="description" type="{http://www.arkivverket.no/dataextracttools/arkade/sessionreport}description" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="datasetDescriptionName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="dataDirectory" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="outputDirectory" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="informationItems" type="{http://www.arkivverket.no/dataextracttools/arkade/sessionreport}informationItems" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="datasetDescription" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="activities" type="{http://www.arkivverket.no/dataextracttools/arkade/sessionreport}activities"/>
 *         &lt;element name="status" type="{http://www.arkivverket.no/dataextracttools/arkade/sessionreport}status" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sessionReport", propOrder = {
    "sessionInformation",
    "datasetDescription",
    "activities",
    "status"
})
@XmlRootElement(name = "sessionReport")
public class SessionReport {

    protected SessionReport.SessionInformation sessionInformation;
    @XmlElement(required = true)
    protected Object datasetDescription;
    @XmlElement(required = true)
    protected Activities activities;
    protected Status status;
    @XmlAttribute(name = "name")
    protected String name;

    /**
     * Gets the value of the sessionInformation property.
     * 
     * @return
     *     possible object is
     *     {@link SessionReport.SessionInformation }
     *     
     */
    public SessionReport.SessionInformation getSessionInformation() {
        return sessionInformation;
    }

    /**
     * Sets the value of the sessionInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link SessionReport.SessionInformation }
     *     
     */
    public void setSessionInformation(SessionReport.SessionInformation value) {
        this.sessionInformation = value;
    }

    /**
     * Gets the value of the datasetDescription property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getDatasetDescription() {
        return datasetDescription;
    }

    /**
     * Sets the value of the datasetDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setDatasetDescription(Object value) {
        this.datasetDescription = value;
    }

    /**
     * Gets the value of the activities property.
     * 
     * @return
     *     possible object is
     *     {@link Activities }
     *     
     */
    public Activities getActivities() {
        return activities;
    }

    /**
     * Sets the value of the activities property.
     * 
     * @param value
     *     allowed object is
     *     {@link Activities }
     *     
     */
    public void setActivities(Activities value) {
        this.activities = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link Status }
     *     
     */
    public Status getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link Status }
     *     
     */
    public void setStatus(Status value) {
        this.status = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="identifiers" type="{http://www.arkivverket.no/dataextracttools/arkade/sessionreport}identifiers" minOccurs="0"/>
     *         &lt;element name="timeCreated" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
     *         &lt;element name="createdBy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="application" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="description" type="{http://www.arkivverket.no/dataextracttools/arkade/sessionreport}description" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="datasetDescriptionName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="dataDirectory" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="outputDirectory" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="informationItems" type="{http://www.arkivverket.no/dataextracttools/arkade/sessionreport}informationItems" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "identifiers",
        "timeCreated",
        "createdBy",
        "application",
        "datasetDescriptionName",
        "dataDirectory",
        "outputDirectory",
        "informationItems"
    })
    public static class SessionInformation {

        protected Identifiers identifiers;
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar timeCreated;
        protected String createdBy;
        protected SessionReport.SessionInformation.Application application;
        protected String datasetDescriptionName;
        protected String dataDirectory;
        protected String outputDirectory;
        protected InformationItems informationItems;

        /**
         * Gets the value of the identifiers property.
         * 
         * @return
         *     possible object is
         *     {@link Identifiers }
         *     
         */
        public Identifiers getIdentifiers() {
            return identifiers;
        }

        /**
         * Sets the value of the identifiers property.
         * 
         * @param value
         *     allowed object is
         *     {@link Identifiers }
         *     
         */
        public void setIdentifiers(Identifiers value) {
            this.identifiers = value;
        }

        /**
         * Gets the value of the timeCreated property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getTimeCreated() {
            return timeCreated;
        }

        /**
         * Sets the value of the timeCreated property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setTimeCreated(XMLGregorianCalendar value) {
            this.timeCreated = value;
        }

        /**
         * Gets the value of the createdBy property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCreatedBy() {
            return createdBy;
        }

        /**
         * Sets the value of the createdBy property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCreatedBy(String value) {
            this.createdBy = value;
        }

        /**
         * Gets the value of the application property.
         * 
         * @return
         *     possible object is
         *     {@link SessionReport.SessionInformation.Application }
         *     
         */
        public SessionReport.SessionInformation.Application getApplication() {
            return application;
        }

        /**
         * Sets the value of the application property.
         * 
         * @param value
         *     allowed object is
         *     {@link SessionReport.SessionInformation.Application }
         *     
         */
        public void setApplication(SessionReport.SessionInformation.Application value) {
            this.application = value;
        }

        /**
         * Gets the value of the datasetDescriptionName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDatasetDescriptionName() {
            return datasetDescriptionName;
        }

        /**
         * Sets the value of the datasetDescriptionName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDatasetDescriptionName(String value) {
            this.datasetDescriptionName = value;
        }

        /**
         * Gets the value of the dataDirectory property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDataDirectory() {
            return dataDirectory;
        }

        /**
         * Sets the value of the dataDirectory property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDataDirectory(String value) {
            this.dataDirectory = value;
        }

        /**
         * Gets the value of the outputDirectory property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOutputDirectory() {
            return outputDirectory;
        }

        /**
         * Sets the value of the outputDirectory property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOutputDirectory(String value) {
            this.outputDirectory = value;
        }

        /**
         * Gets the value of the informationItems property.
         * 
         * @return
         *     possible object is
         *     {@link InformationItems }
         *     
         */
        public InformationItems getInformationItems() {
            return informationItems;
        }

        /**
         * Sets the value of the informationItems property.
         * 
         * @param value
         *     allowed object is
         *     {@link InformationItems }
         *     
         */
        public void setInformationItems(InformationItems value) {
            this.informationItems = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="description" type="{http://www.arkivverket.no/dataextracttools/arkade/sessionreport}description" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "name",
            "version",
            "description"
        })
        public static class Application {

            @XmlElement(required = true)
            protected String name;
            protected String version;
            protected Description description;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the version property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVersion() {
                return version;
            }

            /**
             * Sets the value of the version property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVersion(String value) {
                this.version = value;
            }

            /**
             * Gets the value of the description property.
             * 
             * @return
             *     possible object is
             *     {@link Description }
             *     
             */
            public Description getDescription() {
                return description;
            }

            /**
             * Sets the value of the description property.
             * 
             * @param value
             *     allowed object is
             *     {@link Description }
             *     
             */
            public void setDescription(Description value) {
                this.description = value;
            }

        }

    }

}
